# YAML pipeline build definition
# https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=13760&view=Tab_Tasks
#
# YAML build pipeline based on the Jenkins multi-stage (main branch) build workflow
# https://jenkins.internalx.com/view/Xamarin.MaciOS/job/macios/job/main/
# https://jenkins.internalx.com/view/Xamarin.MaciOS/job/macios/configure
#
resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

  - repository: templates
    type: github
    name: xamarin/yaml-templates
    ref: refs/heads/main
    endpoint: xamarin

variables:
- group: Xamarin-Secrets
- group: Xamarin Release
- group: XamarinCompatLab                                     # provisionator-uri setting
- name: GitHub.Token                                          # Override the GitHub.Token setting defined in the Xamarin Release group
  value: $(github--pat--vs-mobiletools-engineering-service2)  # Use a token dedicated to critical production workflows and help avoid GitHub throttling
- name: system.debug
  value: true

trigger: none

pr:
  autoCancel: true
  branches:
    include:
    - main
    - d16-*

jobs:
- job: Build
  pool:
    vmImage: macOS-10.15

  steps:
  - checkout: self          # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout
    clean: true             # Executes: git clean -ffdx && git reset --hard HEAD
    submodules: recursive

  - powershell: |
      gci env: | format-table -autosize -wrap
    displayName: 'Dump Environment'

  - task: xamops.azdevex.provisionator-task.provisionator@1
    displayName: 'Provision Xcode'
    inputs:
      provisioning_script: $(Build.SourcesDirectory)/tools/devops/provision-xcode.csx
      provisioning_extra_args: '-vvvv'
      github-pat: $(GitHub.Token)
    timeoutInMinutes: 250

  - task: xamops.azdevex.provisionator-task.provisionator@1
    displayName: 'Provision Mono'
    inputs:
      provisioning_script: $(Build.SourcesDirectory)/tools/devops/provision-mono.csx
      provisioning_extra_args: '-vvvv'
      github-pat: $(GitHub.Token)
    timeoutInMinutes: 60

  - task: xamops.azdevex.provisionator-task.provisionator@1
    displayName: 'Provision Brew components'
    inputs:
      provisioning_script: $(Build.SourcesDirectory)/tools/devops/provision-brew-packages.csx
      provisioning_extra_args: '-vvvv'
      github-pat: $(GitHub.Token)
    timeoutInMinutes: 30

  - powershell: |
      if ([IO.Directory]::Exists('/Developer/MonoTouch')) {
        Write-Host "Deleting /Developer/MonoTouch"
        [IO.Directory]::Delete('/Developer/MonoTouch', $True)
      }

      if ([IO.Directory]::Exists('/Library/Frameworks/Xamarin.iOS.framework')) {
        Write-Host "Deleting /Library/Frameworks/Xamarin.iOS.framework"
        [IO.Directory]::Delete('/Library/Frameworks/Xamarin.iOS.framework', $True)
      }

      if ([IO.Directory]::Exists('/Library/Frameworks/Xamarin.Mac.framework')) {
        Write-Host "Deleting /Library/Frameworks/Xamarin.Mac.framework"
        [IO.Directory]::Delete('/Library/Frameworks/Xamarin.Mac.framework', $True)
      }
    displayName: 'Delete library folders'
    timeoutInMinutes: 5
